### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [22]:
# Dependencies and Setup
import pandas as pd
import numpy as np

In [23]:
# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"
# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)
purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
...,...,...,...,...,...,...,...
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,92,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

## Player Count

* Display the total number of players

In [24]:
total_num_players_list = purchase_data["SN"].value_counts()
total_num_players_list

Lisosia93         5
Iral74            4
Idastidru52       4
Siallylis44       3
Hiaral50          3
                 ..
Yarithsurgue62    1
Chamistast30      1
Ermol76           1
Ingatcil75        1
Qilunan34         1
Name: SN, Length: 576, dtype: int64

In [25]:
total_num_players = len(total_num_players_list)
total_num_players

576

In [26]:
total_player_count = pd.DataFrame({"Total Players":[total_num_players]})
total_player_count

   Total Players
0            576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [27]:
#For the number of unique items
no_unique_items = len((purchase_data['Item ID']).unique())
no_unique_items

179

In [28]:
#for average price
avg_price= purchase_data['Price'].mean()
avg_price

3.0509871794871795

In [29]:
#for number of purchases
no_of_purchases = len((purchase_data['Purchase ID'].unique()))
no_of_purchases

780

In [30]:
#for Total Revenue
total_rev = purchase_data['Price'].sum()
total_rev

2379.77

In [31]:
results_df = pd.DataFrame({"Number of Unique Items":[no_unique_items], "Average Price":[avg_price],
                          "Number of purchases":[no_of_purchases], "Total Revenue":[total_rev]})

results_df.style.format({'Average Price':"${:,.2f}",
                        'Total Revenue':"${:,.2f}"})

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [32]:
gender = purchase_data.groupby("Gender")
all_gender = gender.nunique()["SN"]
all_gender

Gender
Female                    81
Male                     484
Other / Non-Disclosed     11
Name: SN, dtype: int64

In [33]:
#percentge of the players with the table
perc_of_players = (all_gender / total_num_players) * 100
gender_table = pd.DataFrame({"Percent of Players": perc_of_players, 
                             "Total Count": all_gender})
gender_table.style.format({'Percent of Players':"{:,.2f}"})


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [34]:
#Total purchase by gender
total_purchase_count = gender['Gender'].count()
total_purchase_count

Gender
Female                   113
Male                     652
Other / Non-Disclosed     15
Name: Gender, dtype: int64

In [35]:
#for average purchase price by gender
avg_purchase_price = gender['Price'].mean()
avg_purchase_price

Gender
Female                   3.203009
Male                     3.017853
Other / Non-Disclosed    3.346000
Name: Price, dtype: float64

In [36]:
#For the total purchase Value
total_purchase = gender['Price'].sum()
total_purchase

Gender
Female                    361.94
Male                     1967.64
Other / Non-Disclosed      50.19
Name: Price, dtype: float64

In [37]:
#average purchase per person
avg_total_purchase_per_person = total_purchase/all_gender
avg_total_purchase_per_person

Gender
Female                   4.468395
Male                     4.065372
Other / Non-Disclosed    4.562727
dtype: float64

In [38]:
#for the Table
purchase_table = pd.DataFrame({"Purchase Count": total_purchase_count,
                              "Average Purchase Price": avg_purchase_price,
                              "Total Purchase Value": total_purchase,
                              "Avg Total Purchase per Person": avg_total_purchase_per_person})
purchase_table.style.format({'Average Purchase Price':"${:,.2f}",
                              'Total Purchase Value':"${:,.2f}",
                        'Avg Total Purchase per Person':"${:,.2f}"})

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [39]:
#for binning the age
bins = [0, 9.9, 14.9, 19.9, 24.9, 29.9, 34.9, 39.9, 80]
group_names = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40+"]

In [40]:
purchase_data['Age Group'] = pd.cut(purchase_data['Age'], bins, labels=group_names)
purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Group
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24
...,...,...,...,...,...,...,...,...
775,775,Aethedru70,21,Female,60,Wolf,3.54,20-24
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,20-24
778,778,Sisur91,7,Male,92,Final Critic,4.19,<10
779,779,Ennrian78,24,Male,50,Dawn,4.60,20-24

In [41]:
grouped_age = purchase_data.groupby("Age Group")
#for total count
age_total_count = grouped_age["SN"].nunique()

#for Percentage
age_percentage = (age_total_count/total_num_players) * 100

In [42]:
#for table
age_table = pd.DataFrame({"Total Count": age_total_count, 
                          "Percentage of Players": age_percentage})
age_table

           Total Count  Percentage of Players
Age Group
<10                 17               2.951389
10-14               22               3.819444
15-19              107              18.576389
20-24              258              44.791667
25-29               77              13.368056
30-34               52               9.027778
35-39               31               5.381944
40+                 12               2.083333

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [43]:
#To count purchases by age group
age_count_purchase = grouped_age['Purchase ID'].count
age_count_purchase()

Age Group
<10       23
10-14     28
15-19    136
20-24    365
25-29    101
30-34     73
35-39     41
40+       13
Name: Purchase ID, dtype: int64

In [44]:
#for the average purchase price
age_avg_purchase_price = grouped_age['Price'].mean()
age_avg_purchase_price

Age Group
<10      3.353478
10-14    2.956429
15-19    3.035956
20-24    3.052219
25-29    2.900990
30-34    2.931507
35-39    3.601707
40+      2.941538
Name: Price, dtype: float64

In [45]:
#for total purchase value
total_purchased_value = grouped_age["Price"].sum()
total_purchased_value

Age Group
<10        77.13
10-14      82.78
15-19     412.89
20-24    1114.06
25-29     293.00
30-34     214.00
35-39     147.67
40+        38.24
Name: Price, dtype: float64

In [46]:
#for Average Total Purchase per Person
avg_total_purchase_per_person = (total_purchased_value/age_total_count)
avg_total_purchase_per_person

Age Group
<10      4.537059
10-14    3.762727
15-19    3.858785
20-24    4.318062
25-29    3.805195
30-34    4.115385
35-39    4.763548
40+      3.186667
dtype: float64

In [48]:
#for the table
purchase_analysis_table =pd.DataFrame({"Purchase Count": age_count_purchase(),
                                 "Average Purchase Price": age_avg_purchase_price,
                                 "Total Purchase Value":total_purchased_value,
                                 "Average Total Purchase per Person": avg_total_purchase_per_person})
purchase_analysis_table.style.format({"Average Purchase Price":"${:,.2f}",
                               "Total Purchase Value":"${:,.2f}",
                               "Average Total Purchase per Person":"${:,.2f}"})

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Total Purchase per Person
Age Ranges,,,,
<10,23,$3.35,$77.13,$4.54
10-14,28,$2.96,$82.78,$3.76
15-19,136,$3.04,$412.89,$3.86
20-24,365,$3.05,"$1,114.06",$4.32
25-29,101,$2.90,$293.00,$3.81
30-34,73,$2.93,$214.00,$4.12
35-39,41,$3.60,$147.67,$4.76
40+,13,$2.94,$38.24,$3.19

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [49]:
money_spent = purchase_data.groupby('SN')
purchase_count_spent = money_spent['Purchase ID'].count()
purchase_count_spent

SN
Adairialis76     1
Adastirin33      1
Aeda94           1
Aela59           1
Aelaria33        1
                ..
Yathecal82       3
Yathedeu43       2
Yoishirrala98    1
Zhisrisu83       2
Zontibe81        3
Name: Purchase ID, Length: 576, dtype: int64

In [50]:
#for average Purchase Price spender
avg_spender = money_spent['Price'].mean()
avg_spender

SN
Adairialis76     2.280000
Adastirin33      4.480000
Aeda94           4.910000
Aela59           4.320000
Aelaria33        1.790000
                   ...
Yathecal82       2.073333
Yathedeu43       3.010000
Yoishirrala98    4.580000
Zhisrisu83       3.945000
Zontibe81        2.676667
Name: Price, Length: 576, dtype: float64

In [51]:
#for the total purchase value
total_spender = money_spent['Price'].sum()
total_spender

SN
Adairialis76     2.28
Adastirin33      4.48
Aeda94           4.91
Aela59           4.32
Aelaria33        1.79
                 ...
Yathecal82       6.22
Yathedeu43       6.02
Yoishirrala98    4.58
Zhisrisu83       7.89
Zontibe81        8.03
Name: Price, Length: 576, dtype: float64

In [52]:
#for the table
spender_table = pd.DataFrame({"Purchase Count": purchase_count_spent,
                             "Average Purchase Price": avg_spender,
                             "Toatal Purchase Value": total_spender})
spender_table

               Purchase Count  Average Purchase Price  Toatal Purchase Value
SN
Adairialis76                1                2.280000                   2.28
Adastirin33                 1                4.480000                   4.48
Aeda94                      1                4.910000                   4.91
Aela59                      1                4.320000                   4.32
Aelaria33                   1                1.790000                   1.79
...                       ...                     ...                    ...
Yathecal82                  3                2.073333                   6.22
Yathedeu43                  2                3.010000                   6.02
Yoishirrala98               1                4.580000                   4.58
Zhisrisu83                  2                3.945000                   7.89
Zontibe81                   3                2.676667                   8.03

[576 rows x 3 columns]

In [55]:
#For in descending order
new_spender_table = spender_table.sort_values(by='Toatal Purchase Value', ascending=False).head()
new_spender_table.style.format({"Average Purchase Price":"${:,.2f}", 
                                 "Toatal Purchase Value":"${:,.2f}"})

             Purchase Count Average Purchase Price Total Purchase Value
SN
Lisosia93                 5                  $3.79               $18.96
Idastidru52               4                  $3.86               $15.45
Chamjask73                3                  $4.61               $13.83
Iral74                    4                  $3.40               $13.62
Iskadarya95               3                  $4.37               $13.10

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [67]:
#Creating a new table for items
items = items = purchase_data[["Item ID", "Item Name", "Price"]]
items

     Item ID                                  Item Name  Price
0        108  Extraction, Quickblade Of Trembling Hands   3.53
1        143                          Frenzied Scimitar   1.56
2         92                               Final Critic   4.88
3        100                                Blindscythe   3.27
4        131                                       Fury   1.44
..       ...                                        ...    ...
775       60                                       Wolf   3.54
776      164                           Exiled Doomblade   1.63
777       67      Celeste, Incarnation of the Corrupted   3.46
778       92                               Final Critic   4.19
779       50                                       Dawn   4.60

[780 rows x 3 columns]

In [68]:
#To group them
item_group = items.groupby(["Item ID", "Item Name"])

#To count them by price
item_count = item_group["Price"].count()
item_count

Item ID  Item Name
0        Splinter                                         4
1        Crucifer                                         4
2        Verdict                                          6
3        Phantomlight                                     6
4        Bloodlord's Fetish                               5
                                                         ..
178      Oathbreaker, Last Hope of the Breaking Storm    12
179      Wolf, Promise of the Moonwalker                  6
181      Reaper's Toll                                    5
182      Toothpick                                        3
183      Dragon's Greatsword                              3
Name: Price, Length: 179, dtype: int64

In [69]:
#To get purchase value
item_value = item_group["Price"].sum()
item_value

Item ID  Item Name
0        Splinter                                         5.12
1        Crucifer                                        11.77
2        Verdict                                         14.88
3        Phantomlight                                    14.94
4        Bloodlord's Fetish                               8.50
                                                         ...
178      Oathbreaker, Last Hope of the Breaking Storm    50.76
179      Wolf, Promise of the Moonwalker                 26.88
181      Reaper's Toll                                    8.30
182      Toothpick                                       12.09
183      Dragon's Greatsword                              3.27
Name: Price, Length: 179, dtype: float64

In [70]:
#To get each item price
item_price = item_value/item_count
item_price

Item ID  Item Name
0        Splinter                                        1.2800
1        Crucifer                                        2.9425
2        Verdict                                         2.4800
3        Phantomlight                                    2.4900
4        Bloodlord's Fetish                              1.7000
                                                          ...
178      Oathbreaker, Last Hope of the Breaking Storm    4.2300
179      Wolf, Promise of the Moonwalker                 4.4800
181      Reaper's Toll                                   1.6600
182      Toothpick                                       4.0300
183      Dragon's Greatsword                             1.0900
Name: Price, Length: 179, dtype: float64

In [71]:
#for the table
item_table = pd.DataFrame({"Purchase Count": item_count,
                          "Item Price": item_price,
                          "Total Purchase Value": item_value})

item_table.style.format({"Item Price":"${:,.2f}",
                            "Total Purchase Value":"${:,.2f}"})

In [73]:
new_item_table = item_table.sort_values(by='Purchase Count', ascending=False).head()
new_item_table.style.format({"Item Price":"${:,.2f}",
                            "Total Purchase Value":"${:,.2f}"})

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
92,Final Critic,13,$4.61,$59.99
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$4.23,$50.76
145,Fiery Glass Crusader,9,$4.58,$41.22
132,Persuasion,9,$3.22,$28.99
108,"Extraction, Quickblade Of Trembling Hands",9,$3.53,$31.77

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [75]:
profitable_items = new_item_table.sort_values(by="Total Purchase Value", ascending=False)
profitable_items.style.format({"Item Price":"${:,.2f}",
                            "Total Purchase Value":"${:,.2f}"})

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
92,Final Critic,13,$4.61,$59.99
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$4.23,$50.76
82,Nirvana,9,$4.90,$44.10
145,Fiery Glass Crusader,9,$4.58,$41.22
103,Singed Scalpel,8,$4.35,$34.80